# The URL the site will be built for
base_url = "https://pixambi.github.io/pixam-zola/"

title = "Pixam Zola"
description = "Demo website for Pixam Zola"

compile_sass = true

build_search_index = false

# Taxonomies
taxonomies = [
    { name = "tags", feed = false }
]

author = "Pixam"

[extra]
