name = "pixam-zola"
description = "Pixam's Zola theme"
tags = ["blog"]
license = "MIT"
homepage = "https://github.com/pixambi/pizam-zola"
min_version = "0.22.0"
demo = "https://pixambi.github.io/pizam-zola/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Pixam"
homepage = "https://pixam.blog/"
